version: '3.8'

networks:
  web-network:
  
services:

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
      args:
        PHP_INI: php.ini-production
        
    container_name: stack-php-fpm
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./src:/var/www/html
      
    environment:
      - BASE_DIR=/var/www/html

      
    networks:
      - web-network

  mysql:
    image: mariadb:10.5.8
    container_name: stack-mariadb
    restart: always
    tty: true
    ports:
      - "3306:3306"    
    volumes:
      - ./data:/var/lib/mysql
      - ./sql/dvwa.sql:/docker-entrypoint-initdb.d/dvwa.sql
    environment:
      MYSQL_DATABASE: dvwa
      MYSQL_USER: danzhu
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - web-network
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: stack-nginx
    volumes:
      - ./src:/var/www/html

    environment:
      - ARG2=${ARG1}
    
    ports:
      - "8080:80"
    networks:
      - web-network
    depends_on:
      - php-fpm
      - mysql