FROM golang:alpine3.16 as builder

WORKDIR /
RUN apk --no-cache add git wget unzip
#RUN wget https://github.com/netxfly/x-crack/archive/refs/heads/master.zip && unzip master.zip && cd x-crack-master  \
RUN git clone https://github.com/netxfly/x-crack && cd x-crack \
&& export GOPROXY=https://proxy.golang.com.cn,direct \
&& GO111MODULE=on go build x-crack.go

FROM alpine:3.16
RUN apk --no-cache add bash git openssh-client ca-certificates bind-tools 

COPY --from=builder /x-crack/x-crack /usr/local/bin/x-crack

ENTRYPOINT ["x-crack"]